apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: production-container
        image: us-west1-docker.pkg.dev/qwiklabs-gcp-03-ad5cf5df1f81/my-repository/hello-cloudbuild:v1.0
        ports:
        - containerPort: 8080
